---
kind: auto.CommandConfig
name: qemu-up
spec:
  disableImage: true
---
kind: common.Image
name: image-provider
spec:
  imageName: omni-infra-provider-bare-metal
  pushLatest: false
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
---
kind: custom.Step
name: ipxe
spec:
  docker:
    enabled: true
    stages:
      - name: ipxe-linux-amd64
        from: ghcr.io/siderolabs/ipxe:v1.10.0-alpha.0-35-g85f8901
        platform: linux/amd64
      - name: ipxe-linux-arm64
        from: ghcr.io/siderolabs/ipxe:v1.10.0-alpha.0-35-g85f8901
        platform: linux/arm64
---
kind: auto.CustomSteps
spec:
  steps:
    - name: ipxe
      toplevel: true
    - name: run-integration-test
      toplevel: true
---
kind: common.Image
name: image-provider
spec:
  pushLatest: false
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
  copyFrom:
    - stage: ghcr.io/siderolabs/musl:v1.10.0-alpha.0-35-g85f8901 # required by zbin
      source: /
      destination: /
    - stage: ghcr.io/siderolabs/liblzma:v1.10.0-alpha.0-35-g85f8901 # required by zbin
      source: /
      destination: /
    - stage: ghcr.io/siderolabs/ipxe:v1.10.0-alpha.0-35-g85f8901
      source: /usr/libexec/zbin
      destination: /bin/zbin
    - stage: ipxe-linux-amd64
      source: /usr/libexec/
      destination: /var/lib/ipxe/amd64
    - stage: ipxe-linux-arm64
      source: /usr/libexec/
      destination: /var/lib/ipxe/arm64
    -
      stage: ghcr.io/siderolabs/talos-metal-agent-boot-assets:v1.9.3-agent-v0.1.2-1-g5cad8b8 # to be used with --use-local-boot-assets for local development
      # stage: 127.0.0.1:5005/siderolabs/talos-metal-agent-boot-assets:v0.0.1-local # for local development, to be replaced with the line above and rekres-ed
      source: /
      destination: /assets
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
---
kind: golang.Generate
spec:
  versionPackagePath: internal/version
  baseSpecPath: /api
  vtProtobufEnabled: true
  specs:
    - source: api/specs/specs.proto
      subdirectory: specs
---
kind: service.CodeCov
spec:
  enabled: false
---
kind: custom.Step
name: run-integration-test
spec:
  sudoInCI: true
  makefile:
    enabled: true
    depends:
      - provider
      - qemu-up
    script:
      - >-
        TEMP_REGISTRY=$(TEMP_REGISTRY)
        OMNI_IMAGE=$(OMNI_IMAGE)
        OMNI_INTEGRATION_TEST_IMAGE=$(OMNI_INTEGRATION_TEST_IMAGE)
        SKIP_CLEANUP=$(SKIP_CLEANUP)
        hack/test/integration.sh
    variables:
      - name: TEMP_REGISTRY
        defaultValue: 127.0.0.1:5005 # local development registry
      - name: OMNI_IMAGE
        defaultValue: ghcr.io/siderolabs/omni:latest
      - name: OMNI_INTEGRATION_TEST_IMAGE
        defaultValue: ghcr.io/siderolabs/omni-integration-test:latest
      - name: SKIP_CLEANUP
        defaultValue: "false"
  ghaction:
    enabled: true
    sops: true
    environment:
      TEMP_REGISTRY: registry.dev.siderolabs.io
    artifacts:
      enabled: true
      extraPaths:
        - "!_out/omni/"
      additional:
        - name: logs
          always: true
          continueOnError: true
          paths:
            - "/tmp/test-logs"
---
kind: common.SOPS
spec:
  enabled: true
  config: |-
    creation_rules:
      - age: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
        # order: Andrey, Noel, Artem, Utku, Dmitriy
        pgp: >-
          15D5721F5F5BAF121495363EFE042E3D4085A811,
          CC51116A94490FA6FB3C18EB2401FCAE863A06CA,
          4919F560F0D35F80CF382D76E084A2DF1143C14D,
          11177A43C6E3752E682AC690DBD13117B0A14E93,
          AA5213AF261C1977AF38B03A94B473337258BFD5
